In [1]:
pip install pymysql

Requirement already satisfied: pymysql in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import json
from datetime import datetime

In [3]:
# this code block allows you to inspect 2 tweets and 2 retweets in the dataset
# it also saves all the unique tweets/retweets in the dictionary tweets
# this code will help you to understand the data
# feel free to print out more fields

lines=0
num_tweets=0
num_retweets=0
print_tweet = 0
print_retweet = 0
tweets = {}

#insert path and replace name of the file below as needed
with open("corona-out-2", "r") as f2:
    for line in f2:
        try:
            data = json.loads(line)
            lines = lines + 1
            if ( data['text'].startswith('RT') ):
                num_retweets += 1
                #print out some fields of one retweet 
                #note that you should look at other fields too
                if (print_retweet < 2):
                    print_retweet += 1
                    # print('RETWEET\n','id--',data['id'],'text--',data['text'],'\n')
                    
                    # print('User-- ',data['user'],'\n')
                  
                    # print('retweetstatus--',data['retweeted_status'],'\n')
                  

            else:
                num_tweets += 1
                #print out some fields of one tweet 
                #note that you should look at other fields too
                if (print_tweet < 2):
                    print_tweet += 1
                    # print('TWEET\n','id--',data['id'],'text--',data['text'],'\n')
                    # print('User-- ',data['user'],'\n')
                    


            if (data['id_str'] not in tweets):
                tweets[data['id_str']] = data
            
        except:
            # if there is an error loading the json of the tweet, skip
            continue
            
# print('num of lines=',lines, 'num of tweets=',num_tweets, 'num of retweets=',num_retweets)
# print('num of unique tweets/retweets=',len(tweets.keys()))

In [4]:
# this code block allows you to inspect 2 tweets and 2 retweets in the dataset
# it also saves all the unique tweets/retweets in the dictionary tweets
# this code will help you to understand the data
# feel free to print out more fields

lines=0
num_tweets=0
num_retweets=0
print_tweet = 0
print_retweet = 0
tweets = {}

#insert path and replace name of the file below as needed
with open("corona-out-3", "r") as f1:
    for line in f1:
        try:
            data = json.loads(line)
            lines = lines + 1
            if ( data['text'].startswith('RT') ):
                num_retweets += 1
                #print out some fields of one retweet 
                #note that you should look at other fields too
                if (print_retweet < 2):
                    print_retweet += 1
                    # print('RETWEET\n','id--',data['id'],'text--',data['text'],'\n')
                    
                    # print('User-- ',data['user'],'\n')
                  
                    # print('retweetstatus--',data['retweeted_status'],'\n')
                  

            else:
                num_tweets += 1
                #print out some fields of one tweet 
                #note that you should look at other fields too
                if (print_tweet < 2):
                    print_tweet += 1
                    # print('TWEET\n','id--',data['id'],'text--',data['text'],'\n')
                    # print('User-- ',data['user'],'\n')
                    


            if (data['id_str'] not in tweets):
                tweets[data['id_str']] = data
            
        except:
            # if there is an error loading the json of the tweet, skip
            continue
            
# print('num of lines=',lines, 'num of tweets=',num_tweets, 'num of retweets=',num_retweets)
# print('num of unique tweets/retweets=',len(tweets.keys()))

In [5]:
import pandas as pd
import json
# Load the dataset into a pandas DataFrame
data_list = []
with open("corona-out-3", "r", encoding="utf-8") as f1:
    for line in f1:
        line = line.strip()  # Remove leading/trailing whitespace
        if not line:
            continue  # Skip empty lines
        try:
            data = json.loads(line)
            data_list.append(data)
        except Exception as e:
            print("Error processing line:", e)
            continue

df = pd.DataFrame(data_list)

In [6]:
import pandas as pd
import json
# Load the dataset into a pandas DataFrame
data_list2 = []
with open("corona-out-2", "r", encoding="utf-8") as f2:
    for line in f2:
        line = line.strip()  # Remove leading/trailing whitespace
        if not line:
            continue  # Skip empty lines
        try:
            data = json.loads(line)
            data_list2.append(data)  # Corrected variable name here
        except Exception as e:
            print("Error processing line:", e)
            continue

df2 = pd.DataFrame(data_list2)

In [7]:

selected_columns = [
    'created_at',
    'id_str',
    'text',
    'user',
    'place',
    'entities',
    'lang',
    'timestamp_ms',
    'retweeted_status'
]

# Selecting the columns
df_selected_corona3 = df[selected_columns]

# Display the first few rows of the new DataFrame with the selected columns
df_selected_corona3.head()

,created_at,id_str,text,user,place,entities,lang,timestamp_ms,retweeted_status
0,Sat Apr 25 12:21:41 +0000 2020,1254022770679320576,"É isto, ou vou morrer sem ar ou com o corona h...","{'id': 804046791348015107, 'id_str': '80404679...",None,"{'hashtags': [], 'urls': [], 'user_mentions': ...",pt,1587817301803,NaN
1,Sat Apr 25 12:21:41 +0000 2020,1254022770746372096,Schöne Runde mit dem Rennrad ✌️\n#sport #coron...,"{'id': 2242948745, 'id_str': '2242948745', 'na...","{'id': '6c741a421f6c33ff', 'url': 'https://api...","{'hashtags': [{'text': 'sport', 'indices': [32...",de,1587817301819,NaN
2,Sat Apr 25 12:21:42 +0000 2020,1254022772558368768,RT @BJP4India: India’s war with Corona is ongo...,"{'id': 908326492718764034, 'id_str': '90832649...",None,"{'hashtags': [], 'urls': [], 'user_mentions': ...",en,1587817302251,{'created_at': 'Sat Apr 25 07:30:12 +0000 2020...
3,Sat Apr 25 12:21:42 +0000 2020,1254022772575043586,Was sollen 150 Euro Computerzuschuss bringen? ...,"{'id': 2929344220, 'id_str': '2929344220', 'na...",None,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",de,1587817302255,NaN
4,Sat Apr 25 12:21:42 +0000 2020,1254022772877131777,RT @schrodingerk42: @ozkan_yalim @DurmusYillma...,"{'id': 1206650133976408064, 'id_str': '1206650...",None,"{'hashtags': [], 'urls': [], 'user_mentions': ...",tr,1587817302327,{'created_at': 'Tue Apr 21 12:34:00 +0000 2020...

In [8]:

df_selected_corona2 = df[selected_columns]

# Display the first few rows of the new DataFrame with the selected columns
df_selected_corona2.head()

,created_at,id_str,text,user,place,entities,lang,timestamp_ms,retweeted_status
0,Sat Apr 25 12:21:41 +0000 2020,1254022770679320576,"É isto, ou vou morrer sem ar ou com o corona h...","{'id': 804046791348015107, 'id_str': '80404679...",None,"{'hashtags': [], 'urls': [], 'user_mentions': ...",pt,1587817301803,NaN
1,Sat Apr 25 12:21:41 +0000 2020,1254022770746372096,Schöne Runde mit dem Rennrad ✌️\n#sport #coron...,"{'id': 2242948745, 'id_str': '2242948745', 'na...","{'id': '6c741a421f6c33ff', 'url': 'https://api...","{'hashtags': [{'text': 'sport', 'indices': [32...",de,1587817301819,NaN
2,Sat Apr 25 12:21:42 +0000 2020,1254022772558368768,RT @BJP4India: India’s war with Corona is ongo...,"{'id': 908326492718764034, 'id_str': '90832649...",None,"{'hashtags': [], 'urls': [], 'user_mentions': ...",en,1587817302251,{'created_at': 'Sat Apr 25 07:30:12 +0000 2020...
3,Sat Apr 25 12:21:42 +0000 2020,1254022772575043586,Was sollen 150 Euro Computerzuschuss bringen? ...,"{'id': 2929344220, 'id_str': '2929344220', 'na...",None,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",de,1587817302255,NaN
4,Sat Apr 25 12:21:42 +0000 2020,1254022772877131777,RT @schrodingerk42: @ozkan_yalim @DurmusYillma...,"{'id': 1206650133976408064, 'id_str': '1206650...",None,"{'hashtags': [], 'urls': [], 'user_mentions': ...",tr,1587817302327,{'created_at': 'Tue Apr 21 12:34:00 +0000 2020...

In [9]:
Corona_df_combined = pd.concat([df_selected_corona2, df_selected_corona3], ignore_index=True)

DATAPREPROCESSING FOR TWEETS

In [10]:
# Initialize lists to store tweet details
created_at = []
tweet_id = []
text = []
user_id = []
tweet_country = []
tweet_language = []
entities_hashtag = []
entities_usermentions = []
date_stamp=[]

# Loop through each entry in the DataFrame
for i in range(0, len(Corona_df_combined)):
    if Corona_df_combined['id_str'][i] and not Corona_df_combined["text"][i].startswith('RT'):
        # Since the tweet is not a retweet, collect its data

        # Convert the string to a datetime object
        date_time_obj = pd.to_datetime(Corona_df_combined["created_at"][i])

        created_at.append(Corona_df_combined["created_at"][i])
        date_stamp.append(date_time_obj.strftime("%Y-%m-%d"))
        tweet_id.append(Corona_df_combined["id_str"][i])
        text.append(Corona_df_combined["text"][i])
        user_id.append(Corona_df_combined["user"][i]['id'])
        tweet_language.append(Corona_df_combined["lang"][i])
        
        # Append country or None if not available
        if Corona_df_combined["place"][i] and 'country' in Corona_df_combined["place"][i]:
            tweet_country.append(Corona_df_combined["place"][i]['country'])
        else:
            tweet_country.append(None)
        
        # Handle user mentions
        if 'user_mentions' in Corona_df_combined["entities"][i]:
            temp_user_mentions = [mention['id'] for mention in Corona_df_combined["entities"][i]['user_mentions']]
            entities_usermentions.append(temp_user_mentions)
        else:
            entities_usermentions.append(None)  # Append None if no user mentions are found

        # Handle hashtags
        if 'hashtags' in Corona_df_combined["entities"][i]:
            temp_hashtags = [hashtag['text'] for hashtag in Corona_df_combined["entities"][i]['hashtags']]
            entities_hashtag.append(temp_hashtags)
        else:
            entities_hashtag.append(None)  # Append None if no hashtags are found

# Create the DataFrame
Tweet_df = pd.DataFrame({
    'CREATED_AT': created_at,
    'DATE_STAMP': date_stamp,
    'TWEET_ID': tweet_id,
    'TEXT': text,
    'USER_ID' : user_id,
    'TWEET_LANGUAGE' : tweet_language,
    'TWEET_COUNTRY' : tweet_country,
    'ENTITIES_HASHTAGS': entities_hashtag,
    'ENTITIES_USER_MENTIONS': entities_usermentions,
})

# Additional processing of hashtags and user mentions
Tweet_df['ENTITIES_HASHTAGS'] = Tweet_df['ENTITIES_HASHTAGS'].apply(lambda x: [str(tag) for tag in set(x)] if isinstance(x, list) and x else None)
Tweet_df['ENTITIES_USER_MENTIONS'] = Tweet_df['ENTITIES_USER_MENTIONS'].apply(lambda x: ["'" + str(mention) + "'" for mention in set(x)] if isinstance(x, list) and x else None)

In [11]:
Tweet_df.head()

,CREATED_AT,DATE_STAMP,TWEET_ID,TEXT,USER_ID,TWEET_LANGUAGE,TWEET_COUNTRY,ENTITIES_HASHTAGS,ENTITIES_USER_MENTIONS
0,Sat Apr 25 12:21:41 +0000 2020,2020-04-25,1254022770679320576,"É isto, ou vou morrer sem ar ou com o corona h...",804046791348015107,pt,None,None,None
1,Sat Apr 25 12:21:41 +0000 2020,2020-04-25,1254022770746372096,Schöne Runde mit dem Rennrad ✌️\n#sport #coron...,2242948745,de,Deutschland,"[sport, corona]",None
2,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022772575043586,Was sollen 150 Euro Computerzuschuss bringen? ...,2929344220,de,None,None,None
3,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022773598572544,@VinceMcMahon @TripleH We hereby honor to anno...,1091660129894838272,en,None,None,"['355708717', '1222639789']"
4,Sat Apr 25 12:21:43 +0000 2020,2020-04-25,1254022776094105602,im making 17 a hr doing nothing 😭😭😭😭 i love th...,375777294,en,None,None,None

In [15]:
tweet_counts = Tweet_df.groupby('USER_ID')['TWEET_ID'].nunique()

# Filter out users with only one tweet
users_with_multiple_tweets = tweet_counts[tweet_counts > 1].reset_index(name='TWEET_COUNT')

print(users_with_multiple_tweets)

                  USER_ID  TWEET_COUNT
0                  608583            2
1                 1281321            3
2                 2062041            2
3                 2902821            2
4                 5734902            2
...                   ...          ...
3561  1254044079882526722            2
3562  1254048425454206976            2
3563  1254050278984335361            3
3564  1254050397548949505            3
3565  1254055557473767425            4

[3566 rows x 2 columns]

In [16]:

# Convert list columns to tuples to make them hashable
Tweet_df['ENTITIES_HASHTAGS'] = Tweet_df['ENTITIES_HASHTAGS'].apply(lambda x: tuple(x) if x is not None else x)
Tweet_df['ENTITIES_USER_MENTIONS'] = Tweet_df['ENTITIES_USER_MENTIONS'].apply(lambda x: tuple(x) if x is not None else x)


# Now try dropping duplicates
Tweet_df = Tweet_df.drop_duplicates()

# Optionally, check how many rows remain
print(f"Number of rows after removing duplicates: {len(Tweet_df)}")

Number of rows after removing duplicates: 40793

In [17]:
Tweet_df.head()

,CREATED_AT,DATE_STAMP,TWEET_ID,TEXT,USER_ID,TWEET_LANGUAGE,TWEET_COUNTRY,ENTITIES_HASHTAGS,ENTITIES_USER_MENTIONS
0,Sat Apr 25 12:21:41 +0000 2020,2020-04-25,1254022770679320576,"É isto, ou vou morrer sem ar ou com o corona h...",804046791348015107,pt,None,None,None
1,Sat Apr 25 12:21:41 +0000 2020,2020-04-25,1254022770746372096,Schöne Runde mit dem Rennrad ✌️\n#sport #coron...,2242948745,de,Deutschland,"(sport, corona)",None
2,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022772575043586,Was sollen 150 Euro Computerzuschuss bringen? ...,2929344220,de,None,None,None
3,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022773598572544,@VinceMcMahon @TripleH We hereby honor to anno...,1091660129894838272,en,None,None,"('355708717', '1222639789')"
4,Sat Apr 25 12:21:43 +0000 2020,2020-04-25,1254022776094105602,im making 17 a hr doing nothing 😭😭😭😭 i love th...,375777294,en,None,None,None

### MONGODB

In [18]:
pip install --upgrade pymongo

Requirement already satisfied: pymongo in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.7.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pymongo) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
%pip install "pymongo[srv]"

Requirement already satisfied: pymongo[srv] in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.7.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pymongo[srv]) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from pymongo.mongo_client import MongoClient
from urllib.parse import quote_plus


username = "preethirameshtce"
password = quote_plus("Preethi@99")  # URL-encode the password

uri = f"mongodb+srv://{username}:{password}@cluster0.mnwlroe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

print(uri)
# Create a new client and connect to the server
client = MongoClient(uri, tlsAllowInvalidCertificates=True)


# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

mongodb+srv://preethirameshtce:Preethi%4099@cluster0.mnwlroe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
Pinged your deployment. You successfully connected to MongoDB!

### STREAMLINING TWEETS - ONE BY ONE - TO MONGODB

In [23]:
import pandas as pd


db_name = "mongo_dbms"  # Name of the database
collection_name = "tweets"  # Name of the collection

# Confirming the connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

# Access database
db = client[db_name]

# Check if the collection exists and drop it
if collection_name in db.list_collection_names():
    db[collection_name].drop()
    print(f"Dropped existing collection: {collection_name}")

# Create a new collection
collection = db[collection_name]


# Convert DataFrame to dictionary format and insert into MongoDB
for index, row in Tweet_df.iterrows():
    row_dict = row.dropna().to_dict()  # Convert row to dictionary, dropping any NaN values
    try:
        collection.insert_one(row_dict)
    except Exception as e:
        # print(f"Failed to insert tweet {row['TWEET_ID']}: {e}")
        continue

# Optional: Close the connection
client.close()
print("Data uploaded and connection closed.")

Pinged your deployment. You successfully connected to MongoDB!
Dropped existing collection: tweets
Data uploaded and connection closed.

### DATAPREPROCESSING FOR RETWEETS

In [21]:
# Initialize lists to store Retweet details
created_at = []
tweet_id = []
text = []
user_id = []
tweet_language = []
entities_hashtag = []
entities_usermentions = []
date_stamp=[]

original_tweet_id = []
in_reply_to_status_id = []
in_reply_to_user_id = []
quote_count = []
reply_count = []
retweet_count = []
favorite_count = []
original_user_id = []
is_quote_status = []
org_lang = []

# Loop through each entry in the DataFrame
for i in range(0, len(Corona_df_combined)):
    if Corona_df_combined['id_str'][i] and Corona_df_combined["text"][i].startswith('RT'):
        # Since the tweet is not a retweet, collect its data
        created_at.append(Corona_df_combined["created_at"][i])
        # Convert the string to a datetime object
        date_time_obj = pd.to_datetime(Corona_df_combined["created_at"][i])
        date_stamp.append(date_time_obj.strftime("%Y-%m-%d"))
        tweet_id.append(Corona_df_combined["id_str"][i])
        text.append(Corona_df_combined["text"][i])
        user_id.append(Corona_df_combined["user"][i]['id'])
        tweet_language.append(Corona_df_combined["lang"][i])
        

        
        # Handle user mentions
        if 'user_mentions' in Corona_df_combined["entities"][i]:
            temp_user_mentions = [mention['id'] for mention in Corona_df_combined["entities"][i]['user_mentions']]
            entities_usermentions.append(temp_user_mentions)
        else:
            entities_usermentions.append(None)  # Append None if no user mentions are found


        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'entities' in Corona_df_combined['retweeted_status'][i] and
                    'hashtags' in Corona_df_combined['retweeted_status'][i]['entities']):
                    
                    temp_hashtags = [hashtag['text'] for hashtag in Corona_df_combined['retweeted_status'][i]['entities']['hashtags']]
                    entities_hashtag.append(temp_hashtags)
        else:
            entities_hashtag.append(None)  # Append None if no hashtags or structure is found


        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'quoted_status' in Corona_df_combined['retweeted_status'][i] and
                    'id_str' in Corona_df_combined['retweeted_status'][i]['quoted_status']):
                    
                    temp_tweetid = Corona_df_combined['retweeted_status'][i]['quoted_status']['id_str']
                    # print(temp_tweetid)
                    original_tweet_id.append(temp_tweetid)
        else:
            
            original_tweet_id.append(None)  



        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'in_reply_to_status_id_str' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['in_reply_to_status_id_str']
                    in_reply_to_status_id.append(temp_val)
        else:
            in_reply_to_status_id.append(None)  # Append None if no hashtags or structure is found
        
        
        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'in_reply_to_user_id_str' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['in_reply_to_user_id_str']
                    in_reply_to_user_id.append(temp_val)
        else:
            in_reply_to_user_id.append(None)  # Append None if no hashtags or structure is found

# quote_count = []


        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'quote_count' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['quote_count']
                    quote_count.append(temp_val)
        else:
            quote_count.append(None)  # Append None if no hashtags or structure is found

# reply_count = []

        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'reply_count' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['reply_count']
                    reply_count.append(temp_val)
        else:
            reply_count.append(None)  # Append None if no hashtags or structure is found


# retweet_count = []

        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'retweet_count' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['retweet_count']
                    retweet_count.append(temp_val)
        else:
            retweet_count.append(None)  # Append None if no hashtags or structure is found

# favorite_count = []

        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'favorite_count' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['favorite_count']
                    favorite_count.append(temp_val)
        else:
            favorite_count.append(None)  # Append None if no hashtags or structure is found

# is_quote_status = []

        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'is_quote_status' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['is_quote_status']
                    is_quote_status.append(temp_val)
        else:
            is_quote_status.append(None)  # Append None if no hashtags or structure is found

# org_lang = []

        if ('retweeted_status' in Corona_df_combined.columns and 
                    pd.notna(Corona_df_combined['retweeted_status'][i]) and 
                    isinstance(Corona_df_combined['retweeted_status'][i], dict) and
                    'lang' in Corona_df_combined['retweeted_status'][i] ):
                    
                    temp_val = Corona_df_combined['retweeted_status'][i]['lang']
                    org_lang.append(temp_val)
        else:
            org_lang.append(None)  # Append None if no hashtags or structure is found



# Create the DataFrame
ReTweet_df = pd.DataFrame({
    'CREATED_AT': created_at,
    'DATE_STAMP': date_stamp,
    'TWEET_ID': tweet_id,
    'TEXT': text,
    'USER_ID' : user_id,
    'TWEET_LANGUAGE' : tweet_language,
    'ENTITIES_HASHTAGS': entities_hashtag,
    'ENTITIES_USER_MENTIONS': entities_usermentions,
    'ORG_TWEET_ID': original_tweet_id,
    'ORG_IN_REPLY_TO_STATUS_ID' : in_reply_to_status_id,
    'ORG_IN_REPLY_TO_USER_ID' : in_reply_to_user_id,
    'ORG_QUOTE_COUNT' : quote_count,
    'ORG_REPLY_COUNT' : reply_count,
    'ORG_RETWEET_COUNT' : retweet_count,
    'ORG_FAVOURITE_COUNT' : favorite_count,
    'ORG_IS_QUOTE_STATUS' : is_quote_status, 
    'ORG_TWEET_LANG' : org_lang,
})

# Additional processing of hashtags and user mentions
ReTweet_df['ENTITIES_HASHTAGS'] = ReTweet_df['ENTITIES_HASHTAGS'].apply(lambda x: ["'" + str(tag) + "'" for tag in set(x)] if isinstance(x, list) and x else None)
ReTweet_df['ENTITIES_USER_MENTIONS'] =  ReTweet_df['ENTITIES_USER_MENTIONS'].apply(lambda x: ["'" + str(mention) + "'" for mention in set(x)] if isinstance(x, list) and x else None)

In [22]:
ReTweet_df

,CREATED_AT,DATE_STAMP,TWEET_ID,TEXT,USER_ID,TWEET_LANGUAGE,ENTITIES_HASHTAGS,ENTITIES_USER_MENTIONS,ORG_TWEET_ID,ORG_IN_REPLY_TO_STATUS_ID,ORG_IN_REPLY_TO_USER_ID,ORG_QUOTE_COUNT,ORG_REPLY_COUNT,ORG_RETWEET_COUNT,ORG_FAVOURITE_COUNT,ORG_IS_QUOTE_STATUS,ORG_TWEET_LANG
0,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022772558368768,RT @BJP4India: India’s war with Corona is ongo...,908326492718764034,en,None,['207809313'],None,None,None,16.0,101.0,340.0,1870.0,False,en
1,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022772877131777,RT @schrodingerk42: @ozkan_yalim @DurmusYillma...,1206650133976408064,tr,None,"['1206650133976408064', '3062441200', '2972639...",None,1252575751259422721,1206650133976408064,1.0,1.0,72.0,83.0,False,tr
2,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022773149589510,RT @MonstaXEurope: VIDEO | 25.04.20\n\n&gt; Mo...,1248123252,en,None,['858859031464751104'],None,None,None,0.0,1.0,41.0,108.0,False,en
3,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022773858545665,RT @gustinicchi: Morti COL Corona non PER il C...,50993809,it,None,['761787475'],None,None,None,1.0,5.0,20.0,29.0,False,it
4,Sat Apr 25 12:21:42 +0000 2020,2020-04-25,1254022774521081856,RT @PawanKalyan: Sri ByReddy Rajasekhar Reddy ...,792325679354417152,en,None,['2719753171'],None,1253697980000960513,2719753171,15.0,45.0,2181.0,7049.0,False,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122219,Sat Apr 25 14:48:38 +0000 2020,2020-04-25,1254059751207395328,RT @detikcom: Bocah 8 tahun yang meninggal dik...,225790145,in,None,['69183155'],None,None,None,140.0,150.0,474.0,1041.0,False,in
122220,Sat Apr 25 14:48:38 +0000 2020,2020-04-25,1254059751949942784,RT @DeepStateExpose: RETWEET! 5G is the real s...,4890378807,en,None,['3580248555'],None,None,None,0.0,0.0,1.0,1.0,False,en
122221,Sat Apr 25 14:48:38 +0000 2020,2020-04-25,1254059752134455296,RT @bongofive: Diamond atangaza kuzilipia kodi...,1196389874351431680,ro,None,['128570166'],None,None,None,9.0,18.0,21.0,220.0,False,ro
122222,Sat Apr 25 14:48:38 +0000 2020,2020-04-25,1254059751945596930,RT @AjeetSonwarsha: “धार्मिक” एक्सपर्ट लोगों स...,872453029,hi,None,['1192032412319928326'],None,None,None,4.0,6.0,97.0,184.0,False,hi
122223,Sat Apr 25 14:48:38 +0000 2020,2020-04-25,1254059752201519104,RT @anderslindberg: För att förstå vad Anders ...,933734367679123456,sv,None,['19236255'],None,None,None,5.0,25.0,21.0,82.0,False,sv

In [23]:

# Convert list columns to tuples to make them hashable
ReTweet_df['ENTITIES_HASHTAGS'] = ReTweet_df['ENTITIES_HASHTAGS'].apply(lambda x: tuple(x) if x is not None else x)
ReTweet_df['ENTITIES_USER_MENTIONS'] = ReTweet_df['ENTITIES_USER_MENTIONS'].apply(lambda x: tuple(x) if x is not None else x)

# Now try dropping duplicates
ReTweet_df = ReTweet_df.drop_duplicates()

# Optionally, check how many rows remain
print(f"Number of rows after removing duplicates: {len(ReTweet_df)}")

Number of rows after removing duplicates: 61101

STREAMLINING TWEETS - ONE BY ONE - TO MONGODB

In [ ]:
import pandas as pd

from pymongo.mongo_client import MongoClient
from urllib.parse import quote_plus


username = "preethirameshtce"
password = quote_plus("Preethi@99")  # URL-encode the password

uri = f"mongodb+srv://{username}:{password}@cluster0.mnwlroe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

print(uri)
# Create a new client and connect to the server
client = MongoClient(uri, tlsAllowInvalidCertificates=True)


db_name = "mongo_dbms"  # Name of the database
collection_name = "ReTweets"  # Name of the collection

# Confirming the connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

# Access database
db = client[db_name]

# Check if the collection exists and drop it
if collection_name in db.list_collection_names():
    db[collection_name].drop()
    print(f"Dropped existing collection: {collection_name}")

# Create a new collection
collection = db[collection_name]

# Convert DataFrame to dictionary format and insert into MongoDB
for index, row in ReTweet_df.iterrows():
    row_dict = row.dropna().to_dict()  # Convert row to dictionary, dropping any NaN values
    try:
        collection.insert_one(row_dict)
    except Exception as e:
        print(f"Failed to insert tweet {row['TWEET_ID']} due to error: {e}")
        continue

# Optional: Close the connection
client.close()
print("Data uploaded and connection closed.")